name: "edit"

# yamllint disable-line rule:truthy 
on:
  push:
    branches: [xr]
permissions:
  contents: write
jobs:
  edit:
    name: edit
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: inspect builder
        run: |
          git config --global user.email "jackhunt43@libero.it"
          git config --global user.name "dragonhunt02"

          #alias rmm='git restore -s main'
          #rm .github/workflows/edit.yaml
          #chmod +x plugins/proxy/command-functions 
          #git reset --soft HEAD~110
          curl -v -o roadmap.tsv -L 'https://docs.google.com/spreadsheets/d/1rNBWaDgqbSmt7ZbWAluyytma9rAH3yhomIihibaceVM/export?gid=993631388&exportFormat=tsv'
          git add -A
          git commit -a -m "Add tsv"
          git push
